version: '3.4'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: '${USER}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:4.0.14
    command: redis-server --appendonly yes --maxmemory 536870912 --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  elasticdata:
  redisdata: