version: '3.4'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: '${USER}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
  elasticdata:
  redisdata: